version: "3.3"
services:
  mpj_db:
    image: 'mysql:8.0.39'
    restart: 'always'
    env_file: ./config/env/.env.development
    expose:
      - "3306"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/db/init_db_local.sql:/docker-entrypoint-initdb.d/init_db_local.sql
      - mysql_data:/var/lib/mysql
  mpj_backend:
    depends_on:
      - mpj_db
    env_file: ./config/env/.env.development
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile.local
      target: development
    ports:
      - "3100:3100"
    volumes:
      - ./:/app
volumes:
  mysql_data: